### ISSUE TITLE
Translate HoareLogic Part 1

### ISSUE THREAD

**Issue by MarisaKirisame** [MarisaKirisame/SFCT#32]

**Comment by zhengyangl** [comment]
:-)

**Comment by lolisa** [comment]
https://github.com/ruoz/SFCTSource/blob/master/Hoare.v
@zhengyangl @ruoz has translated a small part of Hoare, you can continue from there.

**Comment by OlingCat** [comment]
See https://github.com/Coq-zh/SF-zh.
